//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathServiceHost.ServiceModel {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceModel.IMath")]
    public interface IMath {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Prime", ReplyAction="http://tempuri.org/IMath/PrimeResponse")]
        bool Prime(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/Prime", ReplyAction="http://tempuri.org/IMath/PrimeResponse")]
        System.Threading.Tasks.Task<bool> PrimeAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/AddTuple", ReplyAction="http://tempuri.org/IMath/AddTupleResponse")]
        MathService.Tuple AddTuple(MathService.Tuple tuple);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMath/AddTuple", ReplyAction="http://tempuri.org/IMath/AddTupleResponse")]
        System.Threading.Tasks.Task<MathService.Tuple> AddTupleAsync(MathService.Tuple tuple);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathChannel : MathServiceHost.ServiceModel.IMath, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathClient : System.ServiceModel.ClientBase<MathServiceHost.ServiceModel.IMath>, MathServiceHost.ServiceModel.IMath {
        
        public MathClient() {
        }
        
        public MathClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Prime(int value) {
            return base.Channel.Prime(value);
        }
        
        public System.Threading.Tasks.Task<bool> PrimeAsync(int value) {
            return base.Channel.PrimeAsync(value);
        }
        
        public MathService.Tuple AddTuple(MathService.Tuple tuple) {
            return base.Channel.AddTuple(tuple);
        }
        
        public System.Threading.Tasks.Task<MathService.Tuple> AddTupleAsync(MathService.Tuple tuple) {
            return base.Channel.AddTupleAsync(tuple);
        }
    }
}
