// <auto-generated />
using Amigos.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amigos.Migrations
{
    [DbContext(typeof(AmigoDBContext))]
    [Migration("20200331192745_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("Amigos.Models.Amigo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("lati");

                    b.Property<string>("longi");

                    b.Property<string>("name");

                    b.HasKey("ID");

                    b.ToTable("Amigos");
                });
#pragma warning restore 612, 618
        }
    }
}
