// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgetoApi.DataAccessLayer;

namespace ProgetoApi.Migrations
{
    [DbContext(typeof(ProgefileDBContext))]
    [Migration("20200428211419_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("ProgetoApi.Models.Progefile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("code");

                    b.Property<string>("filename");

                    b.Property<string>("path");

                    b.HasKey("ID");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
